#-----------------------------------#
#You can change this
Prefix: '&8[&9SkyWars &8] '
#-----------------------------------#

#-----------------------------------#
#Please do not change this!
Setup: false
PlayerCountToStart: 4
#-----------------------------------#
