name: SkyWars
author: MJ
version: 1.0-SNAPSHOT
main: de.mj.skywars.SkyWars
website: https://github.com/MJGamingHDTV/SkyWars/
description: SkyWars is known by everyone!
database: false

commands:
  setlocation:
    description: Set a location
    usage: Wrong usage! /<command> <lobby, spawn1, spawn2, ...>
    permission: skywars.setup
    aliases: [setloc, set]

permissions:
  skywas.*:
    description: Gives access for all SkyWars commands
    children:
      skywars.setup: true
  skywars.setup:
    description: Gives you the permission to setup the plugin

